# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5003f417603351b1f10e475e0d109d59de2aa408e52bd2a19eaa282964581d878060da0640e4b8534a2d3b0affe9ab32a76a37623b85d86701f8571702f2801e

test:
  secret_key_base: 91ca1a4876674e2a9121e0a26cf4f418189ae6bddaaceeca5a362694936f7a3937539c8dcb94bc5db290b2f63f3ba14041fc12b7c7acc80389071acbd0f51a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
